markdown: kramdown
permalink: /:categories/blog/:year/:month/:day/:title.html
paginate: 5
url: http://ruby-gettext.github.io
gettext_version: 3.1.6
gettext_release_date: 2015-01-20
locale_version: 2.1.2
locale_release_date: 2015-09-15

kramdown:
  enable_coderay: true
  coderay_line_numbers: table
